name: Generating The Test Report

on:
  push:
    branches:
      - main
    # paths:
    #   - '**.java'
    #   - 'pom.xml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Run Automation Tests - Chrome
        run: |
          cd sample-test-case
          mvn clean verify -Dcucumber.filter.tags="@facebook and not @manual" -Dmaven.test.failure.ignore=true -Dwebdriver.remote.url=https://testing-api.mohandurai.info -Dwebdriver.remote.driver=chrome -Dserenity.outputDirectory="chrome-report" -Dcucumber.execution.parallel.enabled=true
      
      - name: Upload Test Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: chrome-report
          path: chrome-report/
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::853973692277:role/mohan-github-role
          role-session-name: GithubActionsSession

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: chrome-report

      - name: Upload Test Results to AWS S3
        run: |
          cd 
          aws s3 sync chrome-report/ s3://testing-md-bucket-results/reports/${{ github.run_number }}/chrome

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id EXKKOLOGFI623 --paths "/*"

      - name: Publish Test Reports
        run: |
          echo "SERENITY REPORTS"
          echo "****************"
          echo "Full Report (Chrome) - https://testing-api.mohandurai.info/reports/${{ github.run_number }}/chrome/index.html"
          echo "Single Page Summary (Chrome) - https://testing-api.mohandurai.info/reports/${{ github.run_number }}/chrome/serenity-summary.html"
          echo "Full Report As React SPA (Chrome) - https://testing-api.mohandurai.info/reports/${{ github.run_number }}/chrome/navigator/index.html"
          echo "****************"
