# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: AWS OIDC

env:
  BUCKET_NAME : "testing-md-bucket-results"
  AWS_REGION : "us-east-1"

on:
  workflow_dispatch:

jobs:
  get_caller_identity:
    name: Deploy Site
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
            
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::853973692277:role/mohan-github-role
          aws-region: us-east-1

      - name: Upload the site contents
        run: |
          echo "hi" >> index.html
          aws s3 cp index.html s3://testing-md-bucket-results/
