name: Generating The Test Report

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_BUCKET_NAME: testing-md-bucket-results
  AWS_ROLE_ARN: arn:aws:iam::853973692277:role/mohan-github-role
  AWS_REGION: us-east-1
  CLOUDFRONT_DISTRIBUTION_ID: EXKKOLOGFI623
  DASHBOARD_ULR: testing-dashboard.mohandurai.info
  SELENIUM_GRID_URL: testing-api.mohandurai.info
    
permissions:
  id-token: write
  contents: read

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Run Automation Tests - Chrome
        run: |
          cd sample-test-case
          mvn clean verify -Dcucumber.filter.tags="@facebook and not @manual" -Dmaven.test.failure.ignore=true -Dwebdriver.remote.url=https://${{ env.SELENIUM_GRID_URL}} -Dwebdriver.remote.driver=chrome -Dserenity.outputDirectory="${{ github.workspace }}/chrome-report" -Dcucumber.execution.parallel.enabled=true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GithubActionsSession

      - name: Upload Test Results to AWS S3
        run: |
          aws s3 sync ${GITHUB_WORKSPACE}/chrome-report/ s3://${{ env.AWS_BUCKET_NAME }}/reports/${{ github.run_number }}/chrome

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

      - name: View Test Reports
        run: |
          echo "---SERENITY REPORTS---"
          echo "Full Report (Chrome) - https://${{ env.DASHBOARD_ULR }}/reports/${{ github.run_number }}/chrome/index.html"
          echo "Single Page Summary (Chrome) - https://${{ env.DASHBOARD_ULR }}/reports/${{ github.run_number }}/chrome/serenity-summary.html"
          echo "Full Report As React SPA (Chrome) - https://${{ env.DASHBOARD_ULR }}/reports/${{ github.run_number }}/chrome/navigator/index.html"
